export const products = [
  {
    id: 1,
    name: "Bột nghệ nguyên chất",
    price: "45.000₫",
    originalPrice: "60.000₫",
    image: "/turmeric-powder-in-glass-jar-natural-lighting.jpg",
    category: "Gia vị",
    sale: true,
    rating: 4.8,
    reviewCount: 32,
    description:
      "Bột nghệ nguyên chất 100% được nghiền từ củ nghệ tươi, giữ nguyên dưỡng chất và màu sắc tự nhiên.",
    ingredients: "100% củ nghệ hữu cơ",
    usage: "Dùng để nấu ăn, làm đẹp da hoặc pha trà nghệ mật ong.",
  },
  {
    id: 2,
    name: "Bột gừng nguyên chất",
    price: "50.000₫",
    image: "/ginger-powder-in-glass-jar-natural-lighting.jpg",
    category: "Gia vị",
    rating: 4.5,
    reviewCount: 28,
  },
  {
    id: 3,
    name: "Bột ớt đỏ",
    price: "55.000₫",
    image: "/red-chili-powder-in-glass-jar-natural-lighting.jpg",
    category: "Gia vị",
    rating: 4.6,
    reviewCount: 24,
  },
  {
    id: 4,
    name: "Bột quế nguyên chất",
    price: "65.000₫",
    originalPrice: "80.000₫",
    image: "/cinnamon-powder-in-glass-jar-natural-lighting.jpg",
    category: "Gia vị",
    sale: true,
    rating: 4.7,
    reviewCount: 18,
  },
  {
    id: 5,
    name: "Hạt tiêu đen nguyên hạt",
    price: "120.000₫",
    image: "/black-peppercorns-in-jar-natural-lighting.jpg",
    category: "Gia vị",
    rating: 4.9,
    reviewCount: 45,
  },
  {
    id: 6,
    name: "Bột tiêu đen",
    price: "95.000₫",
    image: "/black-pepper-powder-in-glass-jar-natural-lighting.jpg",
    outOfStock: true,
    category: "Gia vị",
    rating: 4.4,
    reviewCount: 21,
  },
  {
    id: 7,
    name: "Cà chua sấy khô",
    price: "75.000₫",
    image: "/dried-tomatoes-in-package-natural-lighting.jpg",
    category: "Thực phẩm sấy khô",
    rating: 4.3,
    reviewCount: 15,
  },
  {
    id: 8,
    name: "Nấm rơm sấy khô",
    price: "85.000₫",
    image: "/dried-straw-mushrooms-natural-lighting.jpg",
    category: "Thực phẩm sấy khô",
    rating: 4.5,
    reviewCount: 19,
  },
  {
    id: 9,
    name: "Nấm bào ngư sấy khô",
    price: "150.000₫",
    image: "/dried-oyster-mushrooms-natural-lighting.jpg",
    variants: true,
    category: "Thực phẩm sấy khô",
    rating: 4.8,
    reviewCount: 27,
  },
  {
    id: 10,
    name: "Nước tương tự nhiên lên men",
    price: "65.000₫",
    image: "/fermented-soy-sauce-in-glass-bottle-natural-lighti.jpg",
    category: "Nước tương",
    rating: 4.6,
    reviewCount: 33,
  },
  {
    id: 11,
    name: "Bộ gia vị quà tặng",
    price: "350.000₫",
    originalPrice: "450.000₫",
    image: "/spice-set-gift-box-natural-herbs.jpg",
    variants: true,
    sale: true,
    category: "Bộ quà tặng",
    rating: 4.9,
    reviewCount: 41,
  },
  {
    id: 12,
    name: "Dầu hạt điều nguyên chất",
    price: "180.000₫",
    image: "/cashew-oil-in-glass-bottle-natural-lighting.jpg",
    category: "Dầu ép lạnh",
    rating: 4.7,
    reviewCount: 22,
  },
];
